# Importing Libraries

In [ ]:
import pandas as pd
import numpy as np


# Importing DataSet

In [ ]:
dataset = pd.read_csv("/content/weather.csv")
X = dataset.iloc[:,[0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]].values
Y = dataset.iloc[:,-1].values

In [ ]:
print(X)

[[8.0 24.3 0.0 ... 14.4 23.6 'No']
 [14.0 26.9 3.6 ... 17.5 25.7 'Yes']
 [13.7 23.4 3.6 ... 15.4 20.2 'Yes']
 ...
 [12.5 19.9 0.0 ... 14.5 18.3 'No']
 [12.5 26.9 0.0 ... 15.8 25.9 'No']
 [12.3 30.2 0.0 ... 23.8 28.6 'No']]


In [ ]:
print(Y)

['Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes'
 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes'
 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' '

In [ ]:
Y = Y.reshape(-1,1) #1D list into 2D

In [ ]:
print(Y)

[['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']

# Dealing with Invalid Dataset

In [ ]:
print(X)

[[8.0 24.3 0.0 ... 14.4 23.6 'No']
 [14.0 26.9 3.6 ... 17.5 25.7 'Yes']
 [13.7 23.4 3.6 ... 15.4 20.2 'Yes']
 ...
 [12.5 19.9 0.0 ... 14.5 18.3 'No']
 [12.5 26.9 0.0 ... 15.8 25.9 'No']
 [12.3 30.2 0.0 ... 23.8 28.6 'No']]


In [ ]:
print(Y)

[['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['No']
 ['Yes']
 ['No']

In [ ]:
#it gives some number to the string bcz ML doesnt accept string
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,3] = le1.fit_transform(X[:,3])
le2 = LabelEncoder()
X[:,5] = le2.fit_transform(X[:,5])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,-1] = le3.fit_transform(X[:,-1])
le5 = LabelEncoder()
Y = le5.fit_transform(Y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(X)

[[8.0 24.3 0.0 ... 14.4 23.6 0]
 [14.0 26.9 3.6 ... 17.5 25.7 1]
 [13.7 23.4 3.6 ... 15.4 20.2 1]
 ...
 [12.5 19.9 0.0 ... 14.5 18.3 0]
 [12.5 26.9 0.0 ... 15.8 25.9 0]
 [12.3 30.2 0.0 ... 23.8 28.6 0]]


In [ ]:
print(Y)

[1 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1
 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0
 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1
 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


# Feature Scaling


In [ ]:
#to get the data in range
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [ ]:
print(X)

[[ 0.12204713  0.5612213  -0.33848522 ...  0.36305908  0.65886728
  -0.46904158]
 [ 1.11912864  0.95036308  0.51459076 ...  0.91435303  0.97554878
   2.13200716]
 [ 1.06927456  0.42651837  0.51459076 ...  0.54089584  0.14614485
   2.13200716]
 ...
 [ 0.86985826 -0.09732634 -0.33848522 ...  0.38084276 -0.14037651
  -0.46904158]
 [ 0.86985826  0.95036308 -0.33848522 ...  0.61203054  1.00570892
  -0.46904158]
 [ 0.83662221  1.44427381 -0.33848522 ...  2.0347246   1.41287086
  -0.46904158]]


# Splitting Dataset into Training Dataset and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
#due to this we are getting the data from 2d to 1d

In [ ]:
print(X_train)

[[ 1.43487111  0.42651837 -0.33848522 ...  1.21667552  0.46282635
  -0.46904158]
 [-1.00797857 -0.68103902 -0.33848522 ... -1.0418513  -0.69833916
  -0.46904158]
 [-1.19077684 -0.57627007 -0.33848522 ... -0.5972594  -0.65309895
  -0.46904158]
 ...
 [ 0.95294839  1.14493397 -0.33848522 ...  0.89656936  1.17158971
  -0.46904158]
 [ 0.03895701  0.05234358 -0.33848522 ...  0.52311217  0.08582456
  -0.46904158]
 [-0.80856227  0.0074426  -0.33848522 ... -0.31272059  0.08582456
  -0.46904158]]


In [ ]:
print(Y_train)

[0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1
 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0
 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]


# To replace NAN by mean

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="mean")  # Replace NaN values with the mean
X_train = imputer.fit_transform(X_train)


In [ ]:
print(X_train)

[[ 1.43487111  0.42651837 -0.33848522 ...  1.21667552  0.46282635
  -0.46904158]
 [-1.00797857 -0.68103902 -0.33848522 ... -1.0418513  -0.69833916
  -0.46904158]
 [-1.19077684 -0.57627007 -0.33848522 ... -0.5972594  -0.65309895
  -0.46904158]
 ...
 [ 0.95294839  1.14493397 -0.33848522 ...  0.89656936  1.17158971
  -0.46904158]
 [ 0.03895701  0.05234358 -0.33848522 ...  0.52311217  0.08582456
  -0.46904158]
 [-0.80856227  0.0074426  -0.33848522 ... -0.31272059  0.08582456
  -0.46904158]]


# Training Model

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)

RandomForestClassifier(random_state=0)

In [ ]:
classifier.score(X_train,Y_train)

1.0

In [ ]:
from sklearn.impute import SimpleImputer

# Assuming X_train is your training data
imputer = SimpleImputer(strategy='mean')
X_test_imputed = imputer.fit_transform(X_test)


In [ ]:
print(Y_test)

[0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [ ]:
print(X_test)

[[ 0.58735184  0.69592422 -0.33848522 ...  0.46976114  0.76442778
  -0.46904158]
 [-1.50651932 -1.35455364 -0.33848522 ... -1.96660243 -1.24122174
  -0.46904158]
 [ 1.36839901  0.08227756  0.94112876 ...  0.75429995  0.1159847
   2.13200716]
 ...
 [ 0.18851924 -0.66607202 -0.33848522 ...  0.22078968 -0.60785873
  -0.46904158]
 [ 0.90309431  0.68095723 -0.33848522 ...  0.59424687  0.79458792
  -0.46904158]
 [-1.30710302 -1.2497847  -0.33848522 ... -0.97071659 -1.28646195
  -0.46904158]]


In [ ]:
y_pred = classifier.predict(X_test_imputed)

In [ ]:
print(y_pred)

[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
y_pred = le5.inverse_transform(y_pred)


In [ ]:
print(y_pred)

['No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No']


In [ ]:
print(Y_test)

[0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [ ]:
Y_test = le5.inverse_transform(Y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:155: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(Y_test)

[0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [ ]:
Y_test = Y_test.reshape(-1,1)
y_pred = y_pred.reshape(-1,1)

In [ ]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tomorrow','Prediction of Rain'])


In [ ]:
print(df)

[[0 'No']
 [0 'No']
 [1 'Yes']
 [0 'No']
 [1 'No']
 [1 'No']
 [1 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [1 'No']
 [0 'Yes']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [1 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [1 'No']
 [1 'No']
 [0 'No']
 [1 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [1 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [1 'Yes']
 [1 'Yes']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [1 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']
 [0 'No']]


In [ ]:
print(dataframe)

   Rain on Tomorrow Prediction of Rain
0                 0                 No
1                 0                 No
2                 1                Yes
3                 0                 No
4                 1                 No
..              ...                ...
69                0                 No
70                0                 No
71                0                 No
72                0                 No
73                0                 No

[74 rows x 2 columns]


# Calulating Accuracy


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8513513513513513

In [ ]:
dataframe.to_csv('Prediction.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')